apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nzbhydra2
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: nzbhydra2.local
    http:
      paths:
      - path: /
        backend:
          serviceName: nzbhydra2
          servicePort: 5076
  