---
auth:
  authType: "NONE"
  rememberUsers: true
  rememberMeValidityDays: 14
  restrictAdmin: false
  restrictDetailsDl: false
  restrictIndexerSelection: false
  restrictSearch: false
  restrictStats: false
  allowApiStats: true
  users: []
categoriesConfig:
  enableCategorySizes: true
  categories:
  - name: "Anime"
    mayBeSelected: true
    searchType: "SEARCH"
    newznabCategories:
    - "5070"
    ignoreResultsFrom: "NONE"
    applyRestrictionsType: "BOTH"
    forbiddenRegex: null
    forbiddenWords: []
    requiredRegex: null
    requiredWords: []
    maxSizePreset: 3000
    minSizePreset: 50
    applySizeLimitsToApi: false
    description: null
    preselect: true
    subtype: "ANIME"
  - name: "Audio"
    mayBeSelected: true
    searchType: "MUSIC"
    newznabCategories:
    - "3000"
    ignoreResultsFrom: "NONE"
    applyRestrictionsType: "BOTH"
    forbiddenRegex: null
    forbiddenWords: []
    requiredRegex: null
    requiredWords: []
    maxSizePreset: 2000
    minSizePreset: 1
    applySizeLimitsToApi: false
    description: null
    preselect: true
    subtype: "NONE"
  - name: "Audiobook"
    mayBeSelected: true
    searchType: "MUSIC"
    newznabCategories:
    - "3030"
    ignoreResultsFrom: "NONE"
    applyRestrictionsType: "BOTH"
    forbiddenRegex: null
    forbiddenWords: []
    requiredRegex: null
    requiredWords: []
    maxSizePreset: 1000
    minSizePreset: 50
    applySizeLimitsToApi: false
    description: null
    preselect: true
    subtype: "AUDIOBOOK"
  - name: "Comic"
    mayBeSelected: true
    searchType: "SEARCH"
    newznabCategories:
    - "7030"
    ignoreResultsFrom: "NONE"
    applyRestrictionsType: "BOTH"
    forbiddenRegex: null
    forbiddenWords: []
    requiredRegex: null
    requiredWords: []
    maxSizePreset: 250
    minSizePreset: 1
    applySizeLimitsToApi: false
    description: null
    preselect: true
    subtype: "COMIC"
  - name: "Console"
    mayBeSelected: true
    searchType: "SEARCH"
    newznabCategories:
    - "1000"
    ignoreResultsFrom: "NONE"
    applyRestrictionsType: "BOTH"
    forbiddenRegex: null
    forbiddenWords: []
    requiredRegex: null
    requiredWords: []
    maxSizePreset: 40000
    minSizePreset: 100
    applySizeLimitsToApi: false
    description: null
    preselect: true
    subtype: "NONE"
  - name: "Ebook"
    mayBeSelected: true
    searchType: "BOOK"
    newznabCategories:
    - "7020"
    - "8010"
    ignoreResultsFrom: "NONE"
    applyRestrictionsType: "BOTH"
    forbiddenRegex: null
    forbiddenWords: []
    requiredRegex: null
    requiredWords: []
    maxSizePreset: 100
    minSizePreset: null
    applySizeLimitsToApi: false
    description: null
    preselect: true
    subtype: "EBOOK"
  - name: "FLAC"
    mayBeSelected: true
    searchType: "MUSIC"
    newznabCategories:
    - "3040"
    ignoreResultsFrom: "NONE"
    applyRestrictionsType: "BOTH"
    forbiddenRegex: null
    forbiddenWords: []
    requiredRegex: null
    requiredWords: []
    maxSizePreset: 2000
    minSizePreset: 10
    applySizeLimitsToApi: false
    description: null
    preselect: true
    subtype: "NONE"
  - name: "MP3"
    mayBeSelected: true
    searchType: "MUSIC"
    newznabCategories:
    - "3010"
    ignoreResultsFrom: "NONE"
    applyRestrictionsType: "BOTH"
    forbiddenRegex: null
    forbiddenWords: []
    requiredRegex: null
    requiredWords: []
    maxSizePreset: 500
    minSizePreset: 1
    applySizeLimitsToApi: false
    description: null
    preselect: true
    subtype: "NONE"
  - name: "Movies"
    mayBeSelected: true
    searchType: "MOVIE"
    newznabCategories:
    - "2000"
    ignoreResultsFrom: "NONE"
    applyRestrictionsType: "BOTH"
    forbiddenRegex: null
    forbiddenWords: []
    requiredRegex: null
    requiredWords: []
    maxSizePreset: 20000
    minSizePreset: 500
    applySizeLimitsToApi: false
    description: null
    preselect: true
    subtype: "NONE"
  - name: "Movies HD"
    mayBeSelected: true
    searchType: "MOVIE"
    newznabCategories:
    - "2040"
    - "2050"
    - "2060"
    - "2070"
    ignoreResultsFrom: "NONE"
    applyRestrictionsType: "BOTH"
    forbiddenRegex: null
    forbiddenWords: []
    requiredRegex: null
    requiredWords: []
    maxSizePreset: 20000
    minSizePreset: 3000
    applySizeLimitsToApi: false
    description: null
    preselect: true
    subtype: "NONE"
  - name: "Movies SD"
    mayBeSelected: true
    searchType: "MOVIE"
    newznabCategories:
    - "2030"
    ignoreResultsFrom: "NONE"
    applyRestrictionsType: "BOTH"
    forbiddenRegex: null
    forbiddenWords: []
    requiredRegex: null
    requiredWords: []
    maxSizePreset: 3000
    minSizePreset: 500
    applySizeLimitsToApi: false
    description: null
    preselect: true
    subtype: "NONE"
  - name: "PC"
    mayBeSelected: true
    searchType: "SEARCH"
    newznabCategories:
    - "4000"
    ignoreResultsFrom: "NONE"
    applyRestrictionsType: "BOTH"
    forbiddenRegex: null
    forbiddenWords: []
    requiredRegex: null
    requiredWords: []
    maxSizePreset: 50000
    minSizePreset: 100
    applySizeLimitsToApi: false
    description: null
    preselect: true
    subtype: "NONE"
  - name: "TV"
    mayBeSelected: true
    searchType: "TVSEARCH"
    newznabCategories:
    - "5000"
    ignoreResultsFrom: "NONE"
    applyRestrictionsType: "BOTH"
    forbiddenRegex: null
    forbiddenWords: []
    requiredRegex: null
    requiredWords: []
    maxSizePreset: 5000
    minSizePreset: 50
    applySizeLimitsToApi: false
    description: null
    preselect: true
    subtype: "NONE"
  - name: "TV HD"
    mayBeSelected: true
    searchType: "TVSEARCH"
    newznabCategories:
    - "5040"
    ignoreResultsFrom: "NONE"
    applyRestrictionsType: "BOTH"
    forbiddenRegex: null
    forbiddenWords: []
    requiredRegex: null
    requiredWords: []
    maxSizePreset: 4500
    minSizePreset: 300
    applySizeLimitsToApi: false
    description: null
    preselect: true
    subtype: "NONE"
  - name: "TV SD"
    mayBeSelected: true
    searchType: "TVSEARCH"
    newznabCategories:
    - "5030"
    ignoreResultsFrom: "NONE"
    applyRestrictionsType: "BOTH"
    forbiddenRegex: null
    forbiddenWords: []
    requiredRegex: null
    requiredWords: []
    maxSizePreset: 1000
    minSizePreset: 50
    applySizeLimitsToApi: false
    description: null
    preselect: true
    subtype: "NONE"
  - name: "XXX"
    mayBeSelected: true
    searchType: "SEARCH"
    newznabCategories:
    - "6000"
    ignoreResultsFrom: "NONE"
    applyRestrictionsType: "BOTH"
    forbiddenRegex: null
    forbiddenWords: []
    requiredRegex: null
    requiredWords: []
    maxSizePreset: 10000
    minSizePreset: 100
    applySizeLimitsToApi: false
    description: null
    preselect: true
    subtype: "NONE"
downloading:
  downloaders: []
  saveTorrentsTo: null
  sendMagnetLinks: true
  updateStatuses: true
  showDownloaderStatus: true
indexers:
- allCapsChecked: true
  apiKey: "02537369c0661568425338051f94c446"
  backend: "NEWZNAB"
  categoryMapping:
    anime: 5070
    audiobook: 3030
    comic: 7030
    ebook: 7020
    magazine: 7010
    categories:
    - id: 5000
      name: "TV"
      subCategories:
      - id: 5020
        name: "Foreign"
      - id: 5030
        name: "SD"
      - id: 5040
        name: "HD"
      - id: 5045
        name: "4K"
      - id: 5050
        name: "Other"
      - id: 5060
        name: "Sport"
      - id: 5070
        name: "Anime"
      - id: 5080
        name: "Documentary"
    - id: 2000
      name: "Movies"
      subCategories:
      - id: 2010
        name: "Foreign"
      - id: 2020
        name: "Other"
      - id: 2030
        name: "SD"
      - id: 2040
        name: "HD"
      - id: 2045
        name: "4K"
      - id: 2050
        name: "BluRay"
      - id: 2060
        name: "3D"
      - id: 2070
        name: "Mobile"
    - id: 4000
      name: "Apps"
      subCategories:
      - id: 4010
        name: "0day"
      - id: 4020
        name: "ISO"
      - id: 4030
        name: "Apple"
    - id: 1000
      name: "Gaming"
      subCategories:
      - id: 1010
        name: "NDS"
      - id: 1020
        name: "PSP"
      - id: 1030
        name: "Nintendo"
      - id: 1050
        name: "Xbox 360"
      - id: 1080
        name: "Playstation 3"
      - id: 1090
        name: "Xbox One"
      - id: 1100
        name: "Playstation 4"
      - id: 4050
        name: "PC"
    - id: 3000
      name: "Audio"
      subCategories:
      - id: 3010
        name: "MP3"
      - id: 3020
        name: "Video"
      - id: 3030
        name: "Audiobook"
      - id: 3040
        name: "Lossless"
      - id: 3050
        name: "Other"
    - id: 7000
      name: "Books"
      subCategories:
      - id: 7010
        name: "Magazines"
      - id: 7020
        name: "Ebook"
      - id: 7030
        name: "Comics"
    - id: 6000
      name: "Adult"
      subCategories:
      - id: 6010
        name: "DVD"
      - id: 6020
        name: "WMV"
      - id: 6030
        name: "SD"
      - id: 6040
        name: "HD"
      - id: 6045
        name: "4K"
      - id: 6050
        name: "Pack"
      - id: 6060
        name: "ImgSet"
      - id: 6070
        name: "Other"
    - id: 8000
      name: "Misc"
      subCategories:
      - id: 8010
        name: "Other"
  configComplete: true
  enabledCategories: []
  downloadLimit: null
  state: "ENABLED"
  enabledForSearchSource: "BOTH"
  generalMinSize: null
  hitLimit: null
  hitLimitResetTime: 0
  host: "https://api.dognzb.cr"
  lastError: null
  disabledUntil: null
  disabledLevel: 0
  loadLimitOnRandom: null
  name: "DogNZB"
  password: "7ju$u7kJ"
  preselect: true
  schedule: []
  score: 0
  searchModuleType: "NEWZNAB"
  showOnSearch: true
  supportedSearchIds:
  - "IMDB"
  - "TVRAGE"
  - "TVDB"
  supportedSearchTypes:
  - "TVSEARCH"
  - "MOVIE"
  - "AUDIO"
  timeout: null
  username: "bigdxiii"
  userAgent: null
main:
  apiKey: "88KTNQK0AJ9CPTUJ3AUM0EK62S"
  configVersion: 8
  backupEverySunday: true
  backupBeforeUpdate: true
  deleteBackupsAfterWeeks: 4
  dereferer: "http://www.dereferer.org/?$s"
  databaseCompactTime: 15000
  instanceCounterDownloaded: true
  host: "0.0.0.0"
  logging:
    consolelevel: "INFO"
    historyUserInfoType: "NONE"
    logIpAddresses: true
    mapIpToHost: true
    logMaxHistory: 30
    logfilelevel: "INFO"
    logUsername: false
    markersToLog: []
  port: 5076
  proxyType: "NONE"
  proxyHost: null
  proxyPort: 1080
  proxyIgnoreLocal: true
  proxyIgnoreDomains: []
  proxyUsername: null
  proxyPassword: null
  repositoryBase: "https://github.com/theotherp"
  showNews: true
  shutdownForRestart: false
  sniDisabledFor:
  - "nzbgeek.info"
  ssl: false
  sslKeyStore: null
  sslKeyStorePassword: null
  startupBrowser: true
  theme: "grey"
  urlBase: "/"
  updateCheckEnabled: true
  updateAutomatically: false
  useCsrf: true
  usePackagedCaCerts: true
  verifySsl: true
  verifySslDisabledFor: []
  welcomeShown: true
  xmx: 256
searching:
  applyRestrictions: "NONE"
  duplicateAgeThreshold: 2.0
  duplicateSizeThresholdInPercent: 1.0
  forbiddenGroups: []
  forbiddenPosters: []
  forbiddenRegex: null
  forbiddenWords: []
  generateQueries: "NONE"
  idFallbackToQueryGeneration: "NONE"
  ignorePassworded: false
  ignoreTemporarilyDisabled: false
  ignoreLoadLimitingForInternalSearches: false
  keepSearchResultsForDays: 14
  keepHistoryForWeeks: null
  language: "en_US.UTF-8"
  loadAllCachedOnInternal: true
  maxAge: null
  nzbAccessType: "REDIRECT"
  removeTrailing:
  - ".mp4"
  - ".mkv"
  - ".subs"
  - ".REPOST"
  - "repost"
  - "~DG~"
  - ".DG"
  - "-DG"
  - "-1"
  - ".1"
  - "(1)"
  - "ReUp"
  - "ReUp2"
  - "-RP"
  - "-AsRequested"
  - "-Obfuscated"
  - "-Scrambled"
  - "-Chamele0n"
  - "-BUYMORE"
  - "-[TRP]"
  - "-DG"
  - ".par2"
  - ".part01"
  - "part01.rar"
  - ".part02.rar"
  - ".jpg"
  - "[rartv]"
  - "[rarbg]"
  - "[eztv]"
  - "English"
  - "Korean"
  - "Spanish"
  - "French"
  - "German"
  - "Italian"
  - "Danish"
  - "Dutch"
  - "Japanese"
  - "Cantonese"
  - "Mandarin"
  - "Russian"
  - "Polish"
  - "Vietnamese"
  - "Swedish"
  - "Norwegian"
  - "Finnish"
  - "Turkish"
  - "Portuguese"
  - "Flemish"
  - "Greek"
  - "Hungarian"
  requiredRegex: null
  requiredWords: []
  showQuickFilterButtons: true
  timeout: 20
  transformNewznabCategories: true
  userAgent: "NZBHydra2"
  userAgents:
  - "Mozilla"
  - "Sonarr"
  - "Radarr"
  - "CouchPotato"
  - "LazyLibrarian"
  - "NZBGet"
  - "sabNZBd"
  useOriginalCategories: false
  wrapApiErrors: false
